# --- Variables ---
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}
@username = {{getProfile.response.body.$.user.username}}
@hashedPortfolioUrl = {{connectWithPorttfolio.response.body.$.token}}

# --- User routes ---

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": "075c21597df1c6a1610f"
}

###

# @name getProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

###

# @name getProfileAvatar
GET {{baseUrl}}/users/profile/avatar
Authorization: Bearer {{token}}

###

# @name updatePublicProfile
PATCH {{baseUrl}}/profile/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isPublicProfile": false
}

###

# @name connectWithPorttfolio
POST {{baseUrl}}/users/portfolio/connect
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "portfolioUrl": "https://joaov.vercel.app"
}

###

# @name getPortfolioToken
GET {{baseUrl}}/users/portfolio/token
Authorization: Bearer {{token}}

# --- Projects routes ---

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project API",
  "description": "project description",
  "type": "backend",
  "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo",
    "r4dril0oqwn98r4d8nz8d0wn"
  ],
  "githubUrl": "https://github.com/sercomp"
}

###

# @name findProjectsByUserId
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}

###

# @name findProjectsByUsername
GET {{baseUrl}}/users/{{username}}/projects
# Origin: https://joaov.vercel.app
# Authorization: Bearer {{hashedPortfolioUrl}}

###

# @name getProjectsMetadataByUserId
GET {{baseUrl}}/projects/metadata
Authorization: Bearer {{token}}

###

# @name getStorageMetadataByUserId
GET {{baseUrl}}/projects/storage/metadata
Authorization: Bearer {{token}}

###

# @name findProjectById
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}

###

# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project API Updated",
  "description": "Project description updated",
  "type": "backend",
   "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo"
  ],
  "githubUrl": "https://github.com/project-updated"
}

###

# @name deleteProject
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}

# --- Techs routes ---

###

# @name findAllTechs
GET {{baseUrl}}/techs

# --- Repositories routes ---

###

# @name getUserRepositories
GET {{baseUrl}}/repos
Authorization: Bearer {{token}}

###

# @name getRepositoryData
GET {{baseUrl}}/repos/portfolio
Authorization: Bearer {{token}}
