# --- Variables ---
@baseUrl = http://localhost:3333
@token = {{auth.response.body.$.token}}
@projectId = {{createProject.response.body.$.projectId}}
@username = {{getProfile.response.body.$.user.username}}
@apiKey = {{getApiKey.response.body.$.apiKey}}

# --- User routes ---

###

# @name auth
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": "c296047cae84fe9fb706"
}

###

# @name getProfile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{token}}

###

# @name updateProfileName
PATCH {{baseUrl}}/users/profile/name
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "João Vitor"
}

###

# @name getProfileStatus
GET {{baseUrl}}/users/profile/status
Authorization: Bearer {{token}}

###

# @name updateProfileStatus
PATCH {{baseUrl}}/users/profile/status
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "isPublicProfile": false
}

###

# @name generateApiKey
POST {{baseUrl}}/users/api-key
Authorization: Bearer {{token}}

###

# @name getApiKey
GET {{baseUrl}}/users/api-key
Authorization: Bearer {{token}}

###

# @name deleteApiKey
DELETE {{baseUrl}}/users/api-key
Authorization: Bearer {{token}}

# --- Projects routes ---

###

# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project API",
  "description": "project description",
  "type": "backend",
  "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo",
    "r4dril0oqwn98r4d8nz8d0wn"
  ],
  "githubUrl": "https://github.com/sercomp"
}

###

# @name getProjectsByUserId
GET {{baseUrl}}/projects
Authorization: Bearer {{token}}

###

# @name getProjectsMetadataByUserId
GET {{baseUrl}}/projects/metadata
Authorization: Bearer {{token}}

###

# @name getStorageMetadataByUserId
GET {{baseUrl}}/projects/storage/metadata
Authorization: Bearer {{token}}

###

# @name getProjectById
GET {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}

###

# @name updateProject
PUT {{baseUrl}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Project API Updated",
  "description": "Project description updated",
  "type": "backend",
   "techsIds": [
    "csaqplggm5cnk5gvk1mee53l",
    "dg0mtkuujsnnsmiyrj31e4gn",
    "y7h76rpe9bpu0nyoge75r8uo"
  ],
  "githubUrl": "https://github.com/project-updated"
}

###

# @name deleteProject
DELETE {{baseUrl}}/projects/{{projectId}}
Authorization: Bearer {{token}}

# --- Techs routes ---

###

# @name getAllTechs
GET {{baseUrl}}/techs

# --- Repositories routes ---

###

# @name getRepositoryData
GET {{baseUrl}}/repos/portfolio
Authorization: Bearer {{token}}

# --- Public routes ---

###

# @name getPublicProjects
GET {{baseUrl}}/public/projects/{{username}}?apiKey={{apiKey}}

###

# @name healthCheck
GET {{baseUrl}}/public/health